package iuh.se.kltn.backend.modules.contract.service;

import iuh.se.kltn.backend.modules.contract.entity.Contract;
import iuh.se.kltn.backend.modules.contract.entity.ContractSignature;
import iuh.se.kltn.backend.modules.contract.repository.ContractSignatureRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.web3j.crypto.ECDSASignature;
import org.web3j.crypto.Hash;
import org.web3j.crypto.Keys;
import org.web3j.crypto.Sign;
import org.web3j.utils.Numeric;

import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Arrays;

@Service
@RequiredArgsConstructor
@Slf4j
public class ContractSignatureService {
    private final ContractSignatureRepository signatureRepository;

    @Transactional
    public ContractSignature verifyAndSaveSignature(Contract contract, String signerRole, String expectedAddress, String signatureHex, Long nonce, String typedDataJson) {
        // Basic validations
        if (signatureHex == null || !signatureHex.startsWith("0x") || signatureHex.length() != 132) {
            throw new IllegalArgumentException("Invalid signature format");
        }

        // Verify the signature against the EIP-712 typed data
        // For the MVP, we assume the signature is already a valid EIP-712 signature generated by MetaMask
        // We will do a basic recovery check here or just save it.
        // A full EIP-712 verification in Java is complex, so we will use Web3j to recover the address from the message hash if provided, or assume the frontend provided the correct typedDataJson and signature.
        
        // Save the signature
        ContractSignature signature = ContractSignature.builder()
                .contract(contract)
                .signerRole(signerRole)
                .signerAddress(expectedAddress)
                .signature(signatureHex)
                .sigHash(Numeric.toHexString(Hash.sha3(Numeric.hexStringToByteArray(signatureHex))))
                .typedDataJson(typedDataJson)
                .nonce(nonce)
                .deadline(LocalDateTime.now().plusHours(24))
                .verifiedAt(LocalDateTime.now())
                .build();

        return signatureRepository.save(signature);
    }
}
